apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pull-secret-updater
subjects:
  - kind: ServiceAccount
    name: pull-secret-updater
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: pull-secret-updater
  apiGroup: rbac.authorization.k8s.io
