apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-workload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-workload
  template:
    metadata:
      labels:
        app: test-workload
    spec:
      imagePullSecrets:
      - name: cgr-pull-secret
      containers:
      - name: busybox
        image: cgr.dev/{{ .Values.orgName }}/{{ .Values.imageName }}:latest-dev
        imagePullPolicy: Always
        command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
      restartPolicy: Always
