apiVersion: batch/v1
kind: Job
metadata:
  name: pull-secret-updater
spec:
  backoffLimit: 3
  template:
    spec:
      serviceAccountName: pull-secret-updater
      restartPolicy: Never
      containers:
        - name: pull-secret-updater
          image: {{ .Values.image }}
          imagePullPolicy: Always
          args:
            - --identity={{ .Values.identity }}
